app/web/frontend/urls.py
from . import views
from django.urls import path, include
from django.views.generic import TemplateView

app_name = 'frontend'
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('about/', views.about, name='about'),
    path('posts/', views.show_all_posts, name="show_all_posts"),
  	path('specialposts/', views.show_special_posts, name="show_special_posts"),
    path('users/', views.show_all_users, name='show_all_users'),
    path('users/<int:uid>/', views.user_detail, name='user_detail'),
    path('posts/<int:pid>/', views.post_detail, name='post_detail'),
    path('signup/', views.sign_up, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('logout_success/', views.logout_success, name="logout_success"),
    path('create_listing/', views.create_listing, name='create_listing'),
    path('profile/', views.profile, name='profile'),
    path('profile_update/', views.profile_update, name='profile_update'),
    path('search_listing/', views.search_listing, name='search_listing')
]

app/web/web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('frontend.urls')),
]

app/web/frontend/models.py
from django.db import models

class DummyUser(models.Model):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=30)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    computing_id = models.CharField(max_length=10)
    phone_number = models.CharField(max_length=20)
    bio = models.TextField(max_length=500, blank=True)
    password = models.CharField(max_length=100, default="")

app/web/frontend/forms.py
from django import forms
from .models import *


# class SignUpForm(forms.Form):
#     first_name = forms.CharField(label='First name', max_length=20)
#     last_name = forms.CharField(label='Last name', max_length=20)
#     username = forms.CharField(label='Username', max_length=20)
#     email = forms.EmailField(label='Email', max_length=200)
#     password = forms.CharField(label='Password', widget = forms.PasswordInput())
#     computing_id = forms.CharField(label='Computing ID', max_length=10)
#     phone_number = forms.CharField(label='Phone number', max_length=20)
#     bio = forms.CharField(max_length=500, widget=forms.Textarea(attrs={'cols': 10, 'rows': 4}), required=False)
#     #profile_image = forms.ImageField(default='default.png', upload_to='profile_pics')

#     def __init__(self, *args, **kwargs):
#         super(SignUpForm, self).__init__(*args, **kwargs)


class SignUpForm(forms.ModelForm):
    class Meta:
        model = DummyUser
        fields = ["first_name", "last_name", "username", "email", "password", "computing_id", "phone_number", "bio"]
        widgets = {
            'email': forms.EmailInput(),
            'password': forms.PasswordInput(),
            'phone_number': forms.NumberInput(),
            'bio': forms.Textarea(attrs={'cols': 10, 'rows': 4}),
        }

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['bio'].required = False

    
class LogInForm(forms.Form):
    username = forms.CharField(label='Username', max_length=20)
    password = forms.CharField(label='Password', widget = forms.PasswordInput())


class CreatePostForm(forms.Form):
    title = forms.CharField(max_length=100, label="Title of your post")
    content = forms.CharField(max_length=3000, label="Describe your post briefly", widget=forms.Textarea(attrs={'cols': 10, 'rows': 4}))
    price = forms.FloatField(min_value=0, label="How much do you want to sell for a single swipe?")
    remaining_nums = forms.IntegerField(min_value=0, label="How many swipes do you plan to sell?")
    pickup_address = forms.CharField(max_length=300, label="Where do you plan to meet the buyer?")



class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = DummyUser
        fields = ["username", "email", "first_name", "last_name", "computing_id", "phone_number", "bio"]
        widgets = {
            'email': forms.EmailInput(),
            'phone_number': forms.NumberInput(),
            'bio': forms.Textarea(attrs={'cols': 10, 'rows': 4}),
        }

    def __init__(self, *args, **kwargs):
        super(ProfileUpdateForm, self).__init__(*args, **kwargs)
        self.fields['bio'].required = False

app/web/frontend/views.py
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from urllib.error import URLError, HTTPError
from .forms import SignUpForm, LogInForm, CreatePostForm, ProfileUpdateForm
from django.shortcuts import render, render_to_response
from django.views.generic import TemplateView
from .models import DummyUser
from django.contrib import messages
from django.urls import reverse
import urllib.request
import urllib.parse
import datetime
import json
import socket


def get_uid_by_auth(auth):
    req = urllib.request.Request('http://exp:8000/authenticators/')
    resp_json = urllib.request.urlopen(req).read().decode('utf-8')
    resp = json.loads(resp_json)
    user_id = -1
    for item in resp:
        if item['authenticator'] == auth:
            user_id = item['user_id']
            break
    return user_id


def get_username_by_auth(auth):
    user_id = get_uid_by_auth(auth)
    username_url = 'http://exp:8000/users/' + str(user_id) + "/"
    req = urllib.request.Request(username_url)
    resp_json = urllib.request.urlopen(req).read().decode('utf-8')
    resp = json.loads(resp_json)
    username = ""
    if "error status" in resp.keys():
        username = "NULL"
        return username
    username = resp['username']
    return username


def homepage(request):
    all_posts_req = urllib.request.Request('http://exp:8000/posts/')
    # all_posts_resp_json = urllib.request.urlopen(all_posts_req).read().decode('utf-8')
    try:
        response = urllib.request.urlopen(all_posts_req)
    except urllib.error.URLError as e:
        err_resp = {"error status" : e.code, "error reason": e.reason}
        messages.info(request, e.reason)
        return render(request, 'frontend/homepage.html')
    all_posts_resp_json = response.read().decode('utf-8')
    all_posts_resp = json.loads(all_posts_resp_json)
    if "error status" in all_posts_resp[0].keys():
        return render(request, 'frontend/homepage.html')
    auth = request.COOKIES.get('auth')
    special_posts = show_special_posts(request)
    if auth:
        if check_auth(auth):
            return render(request, 'frontend/homepage.html', {'posts': all_posts_resp, 'special_posts_flag': special_posts['flag'],
                'latest_post' : special_posts['latest_post'], "cheapest_post" : special_posts['cheapest_post'], 
                "most_swipe_post" : special_posts['most_swipe_post']})

    return render(request, 'frontend/homepage.html', {'posts': all_posts_resp, 'special_posts_flag': special_posts['flag'],
        'latest_post' : special_posts['latest_post'], "cheapest_post" : special_posts['cheapest_post'], 
        "most_swipe_post" : special_posts['most_swipe_post']})


def about(request):
    return render(request, 'frontend/about.html')

def show_all_users(request):
    req = urllib.request.Request('http://exp:8000/users/')
    resp_json = urllib.request.urlopen(req).read().decode('utf-8')
    resp = json.loads(resp_json)
    users = {}
    for u in resp:
        users[u['username']] = u
    context = {"test key": "test value"}
    return render(request, "frontend/all_users.html", {'users': users})
   

def user_detail(request, uid):
    url = 'http://exp:8000/users/' + str(uid) + "/"
    req = urllib.request.Request(url)
    resp_json = urllib.request.urlopen(req).read().decode('utf-8')
    resp = json.loads(resp_json)
    err = False
    if "error status" in resp.keys():
        err = True
    else:
        resp.pop("url")
        resp.pop("password")
    return render(request, "frontend/user_detail.html", {'user': resp, 'err': err})


def show_all_posts(request):
    all_posts_req = urllib.request.Request('http://exp:8000/posts/')
    all_posts_resp_json = urllib.request.urlopen(all_posts_req).read().decode('utf-8')
    all_posts_resp = json.loads(all_posts_resp_json)
    return render(request, 'frontend/all_posts.html', {"posts" : all_posts_resp})


def show_special_posts(request):
    all_posts_req = urllib.request.Request('http://exp:8000/posts/')
    all_posts_resp_json = urllib.request.urlopen(all_posts_req).read().decode('utf-8')
    all_posts_resp = json.loads(all_posts_resp_json)

    if (len(all_posts_resp) > 0):
        # get latest post
        latest_post = all_posts_resp[0]
        # get cheapest post and get post with most swipes
        min_price, min_price_index = all_posts_resp[0]["price"], 0
        max_swipe, max_swipe_index = all_posts_resp[0]["remaining_nums"], 0
        for i in range(len(all_posts_resp)):
            post = all_posts_resp[i]
            if (post["price"] < min_price):
                min_price = post["price"]
                min_price_index = i
            if (post["remaining_nums"] > max_swipe):
                max_swipe = post["remaining_nums"]
                max_swipe_index = i
        cheapest_post = all_posts_resp[min_price_index]
        most_swipe_post = all_posts_resp[max_swipe_index]
    else:
        latest_post, cheapest_post, most_swipe_post = "N/A", "N/A", "N/A"

    flag = (len(all_posts_resp) > 0)
    return {'latest_post' : latest_post, 'flag' : str(flag), "cheapest_post" : cheapest_post, "most_swipe_post" : most_swipe_post}
    '''
    return render(request, 'frontend/special_posts.html', {'latest_post' : latest_post, 'flag' : str(flag),
                                                    "cheapest_post" : cheapest_post, "most_swipe_post" : most_swipe_post})
    '''

def get_posts_by_seller(seller_id):
    url = 'http://exp:8000/posts_by_seller/' + str(seller_id) + '/'
    req = urllib.request.Request(url)
    resp_json = urllib.request.urlopen(req).read().decode('utf-8')
    resp = json.loads(resp_json)
    return resp


def post_detail(request, pid):
    url = 'http://exp:8000/posts/' + str(pid) + "/"
    req = urllib.request.Request(url)
    resp_json = urllib.request.urlopen(req).read().decode('utf-8')
    resp = json.loads(resp_json)

    if request.COOKIES.get('logged_in'):
        data = {'user_id' : get_uid_by_auth(request.COOKIES.get('auth')), 'listing_id' : pid}
        data = urllib.parse.urlencode(data).encode()
        view_req = urllib.request.Request('http://exp:8000/listing_views/', data=data)
        try:
            view_response = urllib.request.urlopen(view_req)
        except urllib.error.URLError as e:
            messages.info(request, "Updating access log failed!")
            if resp['ok']:
                return render(request, "frontend/post_detail.html", {'post': resp})
            return render(request, "frontend/post_detail.html")
        view_resp_json = view_response.read().decode('utf-8')
        view_resp = json.loads(view_resp_json)

    if resp['ok']:
        recomm_url = 'http://exp:8000/get_recomm/' + str(pid) + '/'
        recomm_req = urllib.request.Request(recomm_url)
        try:
            recomm_response = urllib.request.urlopen(recomm_req)
        except urllib.error.URLError as e:
            messages.warning(request, "failed to load recommendations in exp layer")
            return render(request, "frontend/post_detail.html", {'post': resp})
        else:
            recomm_resp_json = recomm_response.read().decode('utf-8')
            recomm_resp = json.loads(recomm_resp_json)
            if recomm_resp['ok']:
                recommendations = recomm_resp['recomm']
                return render(request, "frontend/post_detail.html", {'post': resp, 'recommendations': recommendations})
            else:
                if 'err_reason' in recomm_resp:
                    messages.warning(request, "failed to load recommendations in model layer")
                return render(request, "frontend/post_detail.html", {'post': resp})
    else:
        return render(request, "frontend/post_detail.html") 


def sign_up(request):
    if request.COOKIES.get('logged_in'):
        messages.info(request, 'You must log out first to sign up for another account.')
        return HttpResponseRedirect(reverse('frontend:homepage'))
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            data = request.POST
            if ' ' in form.cleaned_data.get("username"):
                messages.warning(request, "Username contains illegal character. Please use another username.")
                dummyuser = DummyUser.objects.create(
                    email = form.cleaned_data.get("email"),
                    username = form.cleaned_data.get("username"),
                    first_name = form.cleaned_data.get("first_name"),
                    last_name = form.cleaned_data.get("last_name"),
                    computing_id = form.cleaned_data.get("computing_id"),
                    phone_number = form.cleaned_data.get("phone_number"),
                    bio = form.cleaned_data.get("bio"))
                empty_form = SignUpForm(instance=dummyuser)
                dummyuser.delete()
                return render(request, 'frontend/signup.html', {'form': empty_form})
            data = urllib.parse.urlencode(data).encode()
            req = urllib.request.Request('http://exp:8000/create_user/', data=data)
            resp_json = urllib.request.urlopen(req).read().decode('utf-8')
            resp = json.loads(resp_json)

            # handle signup error properly
            if not resp["ok"]:
                s = ""
                if resp["err_code"] == 2:
                    s = "Email already exists."
                elif resp["err_code"] == 3:
                    s = "Username already exists."
                messages.warning(request, s)
                # read user's previous inputs to pre-fill the form
                dummyuser = DummyUser.objects.create(
                    email = form.cleaned_data.get("email"),
                    username = form.cleaned_data.get("username"),
                    first_name = form.cleaned_data.get("first_name"),
                    last_name = form.cleaned_data.get("last_name"),
                    computing_id = form.cleaned_data.get("computing_id"),

app/web/frontend/templates/frontend/all_posts.html
{% extends "frontend/base.html" %}
{% load static %}

{% block title %} 
UVA SwipeMe : All Posts
{% endblock title %} 

{% block content %}
<small style="margin: 1% 0 0 5%">
	<i>Note: This page contains some basic info about all the posts. So this is essentially a more reader-friendly version of Post api. 
	This page is static. To view the newest update, please refresh this page.</i>
</small>

{% if posts %}
	<div style="margin: 2% 40% 0% 5%">
		<h4 style="border-bottom:1px solid #ccc!important">All Posts</h4>
		<ul>
    		{% for post in posts %}
    		<div style="margin-top: 3%">
    			<b>{{ post.title }}</b> <small>posted by </small><b><a href="{% url 'frontend:user_detail' post.seller.0.id %}">{{ post.seller.0.first_name }} {{ post.seller.0.last_name }}</a></b> <br>
        		Description: <em>{{ post.content }}</em> <br>
        		<ul>
        			<li>Posted on: {{ post.pub_date }}</li>
					<li>Pick-up Address: {{ post.pickup_address }}</li>
					<li>Price: ${{ post.price }}</li>
					<li>Available Swipes: <b style="color: red">{{ post.remaining_nums }}</b></li>
				</ul>
    		</div>
    		{% endfor %}
    	</ul>
	</div>
{% else %}
	<h1 style="text-align: center">No posts present.</h1>
{% endif %}
{% endblock content%}

app/web/frontend/templates/frontend/all_users.html
{% extends "frontend/base.html" %}
{% load static %}

{% block title %} 
UVA SwipeMe : All Users
{% endblock title %} 

{% block content %}
<div class="note" style="margin: 0% 0 0 5%">
    <small>
        <i>Note: This page contains some basic info about all users and was created during development solely for demo purpose. So this page is essentially a more reader-friendly version of User api.</i>
    </small> <br>
    <small >
        <i>This page is static. To view the newest update, please refresh this page.</i>
    </small>    
</div>

{% if users %}
	<div style="margin: 2% 40% 3% 5%">
		<h4 style="border-bottom:1px solid #ccc!important;">All Users</h4>
		<ul style="margin-top: 2%">
    		{% for key, value in users.items %}
        		<h4><a href="{% url 'frontend:user_detail' value.id %}"> {{ key }} </a></h4>
        		<li>Name: {{ value.first_name }} {{ value.last_name }}</li>
        		<li>Email: {{ value.email }}</li>
        		<li>Computing ID: {{ value.computing_id }}</li>
        		<li>Phone Number: {{ value.phone_number }}</li>
   				<li style="margin-bottom: 2%">{{ value.bio }}</li>
    		{% endfor %}
    	</ul>
	</div>
{% else %}
	<h1 style="text-align: center">No users present.</h1>
{% endif %}
{% endblock content%}

app/web/frontend/templates/frontend/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block head %}{% endblock %}
  <link rel="icon"
        href="https://i.pinimg.com/236x/65/fd/23/65fd23aae970644c82ce0602f00ac525--university-of-virginia-stickers.jpg">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
  <style>
    .fakeimg {
      height: 200px;
      background: #aaa;
    }

    .thumbnail {
      object-fit: contain;
      height: 40px;
      width: 40px;
    }
  </style>
</head>

<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <a class="navbar-brand" href="{% url 'frontend:homepage' %}" style="margin-left: 11%">UVA SwipeMe</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsibleNavbar">
    <span class="navbar-toggler-icon"></span>
  </button>
  <form class="form-inline my-2 my-lg-0" action="{% url 'frontend:search_listing' %}" method="POST">
    {% csrf_token %}
    <input type="text" placeholder="Search listings.." name="search" style="width: 400px;">
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>
  <div class="collapse navbar-collapse" id="collapsibleNavbar" style="margin-left: 30%">
    <ul class="navbar-nav" style="text-align:right">
      
      {% if request.COOKIES.logged_in %}
        <!-- <li class="nav-item"></li>
          <p class="navbar-brand">Hello, {{ request.COOKIES.first_name }}!</p>
        </li>  -->
        <li class="nav-item" type="link">
          <a class="nav-link" href="{% url 'frontend:homepage' %}">Home</a>
        </li>
        <li class="nav-item" type="link">
          <a class="nav-link" href="{% url 'frontend:create_listing' %}">Create listing</a>
        </li>
        <li class="nav-item" type="link">
          <a class="nav-link" href="{% url 'frontend:about' %}">About</a>
        </li>
        <li class="nav-item" type="link">
          <a class="nav-link" href="{% url 'frontend:profile' %}">Profile</a>
        </li>
        <li class="nav-item" type="link">
          <a class="nav-link" href="{% url 'frontend:logout' %}">Log out</a>
        </li>
      {% else %}
        <li class="nav-item" type="link">
          <a class="nav-link" href="{% url 'frontend:homepage' %}">Home</a>
        </li>
        <li class="nav-item" type="link">
          <a class="nav-link" href="{% url 'frontend:about' %}">About</a>
        </li>
        <li class="nav-item" type="link">
          <a class="nav-link" href="{% url 'frontend:login' %}">Log in</a>
        </li>
        <li class="nav-item" type="link">
          <a class="nav-link" href="{% url 'frontend:signup' %}">Sign up</a>
        </li>
      {% endif %}
    </ul>
  </div>
</nav>

<div class="content" style="min-height: 90vh">
  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}
  {% block content %}{% endblock %}
</div>


<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; SwipeMe · Powered by <a href="http://getbootstrap.com" target="_blank">Bootstrap</a>, <a
        href="https://www.w3schools.com" target="_blank">W3Schools</a></small>
    <br>
    <small>Note from developer: currently, we <b>only</b> support meal swipe trade within UVA student community. But we are actively working with students from other universities to gather necessary information so that we can expand our app to student communities in other universities.</small>
  </div>
</footer>
</body>
</html>

app/web/frontend/templates/frontend/homepage.html
{% extends "frontend/base.html" %}
{% load static %}

{% block title %} 
UVA SwipeMe : Home
{% endblock title %} 

{% block head %}
<link rel="stylesheet" type="text/css" href="{% static 'frontend/homepage.css' %}">
{% endblock head %}

{% block content %}

<h1 class="home" style="text-align: center; margin-top: 30px">Homepage</h1>
	{% if posts %}
		<h4 style="border-bottom:1px solid #ccc!important">Listings</h4>
		<div class="row" style="margin: 5px; align-items: center;">
    		{% for post in posts %}
    		<div style="margin-left: 5%; margin-bottom: 2%; width: 300px;">
    			<b><a href="{% url 'frontend:post_detail' post.id %}">{{ post.title }}</a></b>
				<li>Pick-up Address: {{ post.pickup_address }}</li>
				<li>Price: ${{ post.price }}</li>
    		</div>
    		{% endfor %}
		</div>
		<p><a href="{% url 'frontend:show_all_posts' %}">View all listings</a></p> <br>
	{% endif %}
		
	{% if special_posts_flag %}
	<h4 style="border-bottom:1px solid #ccc!important">Discover listings</h4>
	<div class="row" style="margin: 5px; align-items: center;">
		<div class="latest_post" style="margin-left: 5%">
			<h4>Latest Post</h4>
			<b><a href="{% url 'frontend:post_detail' latest_post.id %}">{{ latest_post.title }}</a></b> <small>posted by</small> <b>{{ latest_post.seller.0.first_name }}</b> <br>
			<em>{{ latest_post.content }}</em> <br>
			<ul>
				<li>Pick-up Address: {{ latest_post.pickup_address }}</li>
				<li>Price: ${{ latest_post.price }}</li>
				<li>Available Swipes: <b style="color: red">{{ latest_post.remaining_nums }}</b></li>
			</ul>
		</div>

		<div class="cheapest_post" style="margin-left: 10%">
			<h4>Post with Lowest Price</h4>
			<b><a href="{% url 'frontend:post_detail' cheapest_post.id %}">{{ cheapest_post.title }}</a></b> <small>posted by</small> <b>{{ cheapest_post.seller.0.first_name }}</b> <br>
			<em>{{ cheapest_post.content }}</em><br>
			<ul>
				<li>Pick-up Address: {{ cheapest_post.pickup_address }}</li>
				<li>Price: ${{ cheapest_post.price }}</li>
				<li>Available Swipes: <b style="color: red">{{ cheapest_post.remaining_nums }}</b></li>
			</ul>
		</div>

		<div class="most_swipe_post" style="margin-left: 10%">
			<h4>Post with Most Remaining Swipes</h4>
			<b><a href="{% url 'frontend:post_detail' most_swipe_post.id %}">{{ most_swipe_post.title }}</a></b> <small>posted by</small> <b>{{ most_swipe_post.seller.0.first_name }}</b> <br>
			<em>{{ most_swipe_post.content }}</em><br>
			<ul>
				<li>Pick-up Address: {{ most_swipe_post.pickup_address }}</li>
				<li>Price: ${{ most_swipe_post.price }}</li>
				<li>Available Swipes: <b style="color: red">{{ most_swipe_post.remaining_nums }}</b></li>
			</ul>
		</div>
	</div>
	<!-- <p class="text-right"><a href="{% url 'frontend:show_special_posts' %}">Discover posts</a> <br></p> -->
	{% endif %}

	
	<a href="{% url 'frontend:show_all_users' %}">View all users</a> <br>

<!--
		<div class="container-fluid">
			<div id="carouselExample" class="carousel slide" data-ride="carousel" data-interval="9000">
				<div class="carousel-inner row w-100 mx-auto" role="listbox">
					{% for post in posts %}
						{% if forloop.first %}
						<div class="carousel-item col-md-3 active">
						{% else %}
						<div class="carousel-item col-md-3">
						{% endif %}
							<div style="width: 200px; height: 150px; background-color: lightgrey;">
								<b><a href="{% url 'frontend:post_detail' post.id %}">{{ post.title }}</a></b>
							
								<li>Location: {{ post.pickup_address }}</li>
								<li>Price: ${{ post.price }}</li>
							</div>
						</div>
					{% endfor %}
				</div>
				<a class="carousel-control-prev" href="#carouselExample" role="button" data-slide="prev" style="background-color: lightgrey;">
					<i class="fa fa-chevron-left fa-lg text-muted"></i>
					<span class="sr-only">Previous</span>
				</a>
				<a class="carousel-control-next text-faded" href="#carouselExample" role="button" data-slide="next" style="background-color: lightgrey;">
					<i class="fa fa-chevron-right fa-lg text-muted"></i>
					<span class="sr-only">Next</span>
				</a>
			</div>
		</div>
-->


</div>

<script>
	$('#carouselExample').on('slide.bs.carousel', function (e) {

	var $e = $(e.relatedTarget);
	var idx = $e.index();
	var itemsPerSlide = 3;
	var totalItems = $('.carousel-item').length;

	if (idx >= totalItems-(itemsPerSlide-1)) {
		var it = itemsPerSlide - (totalItems - idx);
		for (var i=0; i<it; i++) {
			// append slides to end
			if (e.direction=="left") {
				$('.carousel-item').eq(i).appendTo('.carousel-inner');
			}
			else {
				$('.carousel-item').eq(0).appendTo('.carousel-inner');
			}
		}
	}
	});
</script>

{% endblock content %}

app/web/frontend/templates/frontend/post_detail.html
{% extends "frontend/base.html" %}
{% load static %}

{% block title %} 
UVA SwipeMe : Post Detail
{% endblock title %} 


{% block content %}

{% if not post %}
    <h2 style="text-align: center">Listing not found!</h2>
{% else %}
    <ul>
        <h3>{{ post.title }}</h3>
        <p>by <a href="{% url 'frontend:user_detail' post.seller.0.id %}">{{ post.seller.0.first_name }} {{ post.seller.0.last_name }}</a></p>
        <h6>{{ post.content }}</h6>
        <li>Price: ${{ post.price }}</li>
        <li>Pick up at: {{ post.pickup_address }}</li>
        <li>Remaining swipe: {{ post.remaining_nums }}</li>
        <li>Posted on: {{ post.pub_date|slice:"0:10" }}</li>
        <!--
    {% for key, value in post.items %}
    {% if key == 'seller' %}
        <li>{{ key }}: <a href="{% url 'frontend:user_detail' value.0.id %}">{{ value.0.first_name }} {{ value.0.last_name }}</a> </li>
    {% else %}
        {% if key != 'url' and key != 'id'%}
            <li>{{ key }}: {{ value }}</li>
        {% endif %}
    {% endif %}
    {% endfor %}
        -->
    </ul>

    {% if recommendations %}
        <b>People who looked at this listing also looked at:</b>
        <div class="row" style="margin: 5px; align-items: center;">
          {% for recomm in recommendations %}
          <div style="margin-left: 5%; margin-bottom: 2%; width: 300px;">
            <b><a href="{% url 'frontend:post_detail' recomm.id %}">{{ recomm.title }}</a></b>
          <li>Pick-up Address: {{ recomm.pickup_address }}</li>
          <li>Price: ${{ recomm.price }}</li>
          </div>
          {% endfor %}
        </div>
    {% else %}
        <b>There are currently no recommendations available for this listing.</b>
    {% endif %}

{% endif %}

{% endblock content %}